# Variable declaration
CC = gcc
CFLAGS = -Wall -lm

# General compiling rule
all:
	$(CC) -o ex1a ex1a.c $(CFLAGS)
	$(CC) -o ex1b ex1b.c $(CFLAGS)
	$(CC) -o ex1c ex1c.c $(CFLAGS)
	$(CC) -o ex1d ex1d.c $(CFLAGS)
	$(CC) -o ex1e1 ex1e1.c $(CFLAGS)
	$(CC) -o ex1e2 ex1e2.c $(CFLAGS)
	$(CC) -o ex1e3 ex1e3.c $(CFLAGS)
	$(CC) -o ex1f1 ex1f1.c $(CFLAGS)
	$(CC) -o ex1f2 ex1f2.c $(CFLAGS)
	$(CC) -o ex1g1 ex1g1.c $(CFLAGS)
	$(CC) -o ex1g2 ex1g2.c $(CFLAGS)
	$(CC) -o ex1h1 ex1h1.c $(CFLAGS)
	$(CC) -o ex1h2 ex1h2.c $(CFLAGS)
	$(CC) -o parity parity.c $(CFLAGS)
	$(CC) -o counter counter.c $(CFLAGS)
	$(CC) -o triangle triangle.c $(CFLAGS)
	$(CC) -o random random.c $(CFLAGS)

# Cleaning (used to remove intermediate files and / or results)
.PHONY : clean
clean :
	rm -f ex1a ex1b ex1c ex1d ex1e1 ex1e2 ex1e3 ex1f1 ex1f2 ex1g1 ex1g2 ex1h1 ex1h2 parity counter triangle random *~
